# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Falu < Formula
  desc "Falu CLI"
  homepage "https://falu.io"
  license "MIT"
  version "1.10.0"

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/1.10.0/falu-1.10.0-linux-arm64.tar.gz"
      sha256 "453316006e21a0dbc22ae1cc85e53e20df70fe7c0e670d78a009855bfa474c9e"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/1.10.0/falu-1.10.0-linux-x64.tar.gz"
      sha256 "cfd5d25d3aac34bb3d9837050abed010baa097385da78f200c36667fe1063684"
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/1.10.0/falu-1.10.0-osx-arm64.tar.gz"
      sha256 "ae806ce98cf95ff75e71c4519a9d9493a155314459591fef0a4c69b43cc1aa1e"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/1.10.0/falu-1.10.0-osx-x64.tar.gz"
      sha256 "79f57b510c89007eba66982898d64064a857572d7a6f3e27b61133cf64f1e169"
    end
  end

  def install
    bin.install "falu"
  end

  test do
    system "#{bin}/falu", "--version"
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Falu CLI! If this is your first time using the CLI, be sure to run `falu login` first.
  EOS
  end
end