# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Falu < Formula
  desc "Falu CLI"
  homepage "https://falu.io"
  license "MIT"
  version "0.11.0"

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/0.11.0/falu-0.11.0-linux-arm64.tar.gz"
      sha256 "a37cecae03bba85674a9ac946f42ee5e2013d65111f4169131cb453bc929d96a"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/0.11.0/falu-0.11.0-linux-x64.tar.gz"
      sha256 "e84debea5edea82858d55a064a978287bba41bceacb25834a0d1a81e243979a5"
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/0.11.0/falu-0.11.0-osx-arm64.tar.gz"
      sha256 "40faa67de100d6ff4479591d12b697e9c916a2dec6cc933ce30a90a47a57b014"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/0.11.0/falu-0.11.0-osx-x64.tar.gz"
      sha256 "ed08cd74a905b725acba3583fb0dbe9a08507cc3d7faeb21984a45a46c145d62"
    end
  end

  def install
    bin.install "falu"
  end

  test do
    system "#{bin}/falu", "--version"
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Falu CLI! If this is your first time using the CLI, be sure to run `falu login` first.
  EOS
  end
end