# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Falu < Formula
  desc "Falu CLI"
  homepage "https://falu.io"
  license "MIT"
  version "0.12.0"

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/0.12.0/falu-0.12.0-linux-arm64.tar.gz"
      sha256 "1a9786fc896f696481229d40ff980dce4d7681c7bc1392d2f8bf895b92b64911"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/0.12.0/falu-0.12.0-linux-x64.tar.gz"
      sha256 "646e5e03d273061c85b469d0b86a84d2402be41f8b4f170809dc62e341bd0029"
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/0.12.0/falu-0.12.0-osx-arm64.tar.gz"
      sha256 "e7e5a953b85d91aa8ea4bad668876db043d4441cf35ccaf020434dbfccb22c75"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/0.12.0/falu-0.12.0-osx-x64.tar.gz"
      sha256 "03c8c6e067094a0637e3c10c8f4e00a9200d763b291377d8ff520f7573bdf592"
    end
  end

  def install
    bin.install "falu"
  end

  test do
    system "#{bin}/falu", "--version"
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Falu CLI! If this is your first time using the CLI, be sure to run `falu login` first.
  EOS
  end
end